### ISSUE TITLE
Tests: Failure during map testing when CI environment is false

### ISSUE THREAD

**Issue by StormyDragon** [ScavStation/Baystation12#123]
The autogenerated file `code/_helpers/global_access.dm` is suppressed when `CI` is false, leading to the test using the checked out version instead. Checkout rules say that line endings of checked out files must be CRLF, but the tool generates LF, so that test will fail always when `CI` is false.

Without going into the deep rabbit hole that is Global Variables and Garbage Collection that is the origin of this datastructure, ideally we would generate and include this file whenever the game is built and never allow it to see the repository.

Perhaps a more pressing question; what is this actually testing?

**Comment by afterthought2** [comment]
To answer the more general question: prior to byond version 512, there was no way to access a list of all global variables at runtime. Doing so is desirable for debugging purposes and VV, so the script automatically finds all the global vars in the code (from the object tree, which is available on compile) and adds them in (essentially) a list to the code, so they can be accessed. The reason this is done user-side and tested instead of during build is to simplify the build toolchain.

As of byond version 512, `global.vars` serves the same purpose, so this system is no longer needed.
